- name: common
  scm: git
  src: "git@github.com:Diesel-Net/ansible-role-common.git"
  version: 1.2.0

- name: docker
  scm: git
  src: "git@github.com:Diesel-Net/ansible-role-docker.git"
  version: 1.10.0
